<?php

namespace KevinGH\Bcrypt\Exception;

use InvalidArgumentException;

/**
 * This exception is thrown if the encoded string used was not a string that
 * would have been generated by the Blowfish encoding function. It could also
 * mean that the string used was not encoded at all.
 *
 * @author Kevin Herrera <kevin@herrera.io>
 */
class InvalidEncodedStringException extends InvalidArgumentException
{
    /**
     * The invalid encodedString.
     *
     * @var string
     */
    private $encodedString;

    /**
     * Sets the invalid encodedString.
     *
     * @param string $encodedString The invalid encoded string.
     */
    public function __construct($encodedString)
    {
        $this->encodedString = $encodedString;
    }

    /**
     * Returns the invalid encodedString.
     *
     * @return string The invalid encoded string.
     */
    public function getEncodedString()
    {
        return $this->encodedString;
    }
}
